name: Bug Report
description: Create a report to help us improve svelte-idb
title: '[BUG] '
labels: ['bug', 'triage']
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Before submitting a bug, please make sure it hasn't been fixed in the latest version of `svelte-idb`, and search existing issues to see if it's already reported.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior, or ideally a link to a minimal reproduction repository (like a StackBlitz, CodeSandbox, or GitHub repo).
      placeholder: |
        1. createReactiveDB(...)
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: svelte-idb Version
      description: The version you are using.
      placeholder: '0.1.0'
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Are you using this in a browser, SSR, or both?
      options:
        - Browser only
        - SSR only
        - Both
    validations:
      required: true
